### PR TITLE
fix ExtDeprecationWarning

### LINKED ISSUE #15: flask.ext.login import Warning
relates to issue #13.

The offending code is located in the `flask_rbac/__init__.py` [file](https://github.com/shonenada/flask-rbac/blob/master/flask_rbac/__init__.py#L19).
```python
try:
    from flask.ext.login import current_user
except ImportError:
    current_user = None
```
This yiels a 
```shell
ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
```
warning.

### PR DESCRIPTION
**Pull request by trendsetter37**
when importing flask_login extension.

closes #15

### CODE REVIEW

**Comment by shonenada** [comment]
@trendsetter37 Thank you so much, bug there is a error in https://travis-ci.org/shonenada/flask-rbac/builds/161157813. I have fixed that. Please rebase `master` , and push with `-force`x.

**Comment by trendsetter37** [comment]
@shonenada Done.

**Comment by shonenada** [comment]
LGTM

**Comment by shonenada** [comment]
@trendsetter37 Thank you .

**Pull request merged**
