### PR TITLE
improve performance of _check_permission method

### PR DESCRIPTION
**Pull request by hieuvo**

### CODE REVIEW

**Comment by hieuvo** [comment]
@shonenada : just a tiny change and it helps to reduce the running time of `__authenticate` method from 200ms to 10s for my application

**Comment by shonenada** [comment]
LGTM，thanks a lot @hieuvo

**Comment by shonenada** [comment]
@hieuvo now available with version 0.4.0

**Comment by hieuvo** [comment]
@shonenada : if it's possible, please help to pump up flask-rbac's tag version, then I can include it to my application

**Comment by hieuvo** [comment]
> @hieuvo now available with version 0.4.0

thanks @shonenada

**Pull request merged**
